### ISSUE TITLE
Adyen redirect URL does not generate Sales Channel correct URL (missing domain info)

### ISSUE THREAD

**Issue by damyanovg** [Adyen/adyen-shopware6#267] opened 2022-07-04 08:49 UTC
This issue was first mentioned here:
https://github.com/Adyen/adyen-shopware6/issues/136

and was supposed to be fixed with the following PR:
https://github.com/Adyen/adyen-shopware6/pull/137/files

We've tested this with the newest Adyen & Shopware 6 version but the sales channel is still missing from the redirect url.

**To Reproduce**

- Create a sales channel with a domain like https://www.example.com/en and only that URL.
- Add a product to the cart and choose a payment method like Sofort.
- Finish the order with the test data.
- This will result in a payment redirect URL like: `https://www.example.com/adyen/redirect-result?_csrf_token=....&_sw_payment_token=....`
- The redirect URL should be:  `https://www.example.com/en/adyen/redirect-result?_csrf_token=....&_sw_payment_token=....`

**Comment by Morerice** [comment] 2022-07-13 14:15
Hi @damyanovg,

Thanks for opening this issue as well as providing clear steps to reproduce. We will attempt to reproduce this issue and understand if and why our fix is not working.

Best regards,
Jean
Adyen

**Comment by Morerice** [comment] 2022-08-03 08:43
Hi @damyanovg,

Apologies for the delay. We have identified some cases our previous fix will not correct this issue. The issue is that in the [SalesChannelRepository](https://github.com/Adyen/adyen-shopware6/blob/4c189034715a9129ce5034f405ff3c35314333e7/src/Service/Repository/SalesChannelRepository.php#L50) we are always getting only the first domain that has been linked to this sales channel.

The main uncertainty from our end right now is that we're still looking for a way to obtain the current `domain` that is in use. If we can obtain that, we can easily filter all the domains obtained from the salesChannel and return the correct one. Feel free to reach out to us if you have any suggestions.

Thanks,
Jean
Adyen

**Comment by mKnoop** [comment] 2022-08-25 15:07
Hey @Morerice,

we used a combination of the the request attributes (SALES_CHANNEL_BASE_URL, STOREFRONT_URL) and the global $_SERVER variable HTTP_HOST in an old fix for this problem in a previous shopware version. With this you should detect the used domain for the current request. If the mentioned attributes are not working, the request should contain a few more attributes that could help: [RequestTransformer](https://github.com/shopware/platform/blob/trunk/src/Storefront/Framework/Routing/RequestTransformer.php)

**Comment by Morerice** [comment] 2022-08-29 11:12
Hi @mKnoop,

Thanks for the suggestion. This could definitely be a possible solution. My only question (that we have to look into) is if it is possible to find an alternative to avoid using the `$_SERVER` superglobal. 

Thanks,
Jean
Adyen

**Comment by andydandy80** [comment] 2022-08-31 14:51
We have the same problem. When will it be fixed?

**Comment by andydandy80** [comment] 2022-09-01 07:49
In your RedirectResultController you are calling in function "execute" the shopware PaymentController:
`$this->paymentController->finalizeTransaction($request, $salesChannelContext)`

The shopware PaymentController and function "finalizeTransaction" has no second parameter in version 6.4.13.0.

Please check this, the plugin is currently not useable for us and our customer.

**Closed** 2022-09-07 15:21 UTC
