### ISSUE TITLE
[ECP-8838] NS_BINDING_ABORTED on cancel paypal payment.

### ISSUE THREAD

**Issue by cwittstock** [Adyen/adyen-shopware6#438] opened 2023-12-06 09:13 UTC
**Describe the bug**
If a payment via Paypal is canceled, the payment status remains "in process". This happens because the Ajax request (POST) to the endpoint /adyen/proxy-cancel-order-transaction is canceled due to a redirect (location.href).
The browser acknowledges the request with "NS_BINDING_ABORTED".

**Versions**
Shopware version: 6.4.20.2
Plugin version: 3.14.2

**To Reproduce**
First, the payment method Paypal must be selected in the checkout. Then click on the Paypal button to complete the payment. In the small window that opens, you can then click on "Cancel and return to ..." - or you simply close the window. Unfortunately, the payment status then remains "In progress".

**Expected behavior**
For every other payment method, the payment status changes to "canceled". I would also expect this with PayPal. If I then send the POST again manually, the payment status also changes to "canceled".

**Comment by candemiralp** [comment] 2023-12-22 09:16
Hello @cwittstock,

Thank you for raising this issue. We've created an internal ticket to investigate and solve this issue. You will be informed when the investigation is completed.

Best Regards,
Can

**Comment by candemiralp** [comment] 2024-05-08 10:13
Hello @cwittstock,

We have finalised the investigation but unfortunately we are not able to reproduce the issue on the given versions or on the latest versions of both plugin and Shopware 6. As you can see from the screenshot, we managed to get `Cancelled` status every time we click `Cancel and Return to ...` button.

<img width="1307" alt="image" src="https://github.com/Adyen/adyen-shopware6/assets/20255503/350146ec-cf39-406d-912e-3d1adab1cabd">

Please let us know if you have any other useful tips fro reproducing this issue.

Best regards,
Can

**Comment by candemiralp** [comment] 2024-05-21 07:10
Closing this issue since it can not be reproduced on a fresh instance and it requires more information. Please open a new issue if the issue is persistent on your instance.

Best regards,
Can

**Closed by candemiralp** 2024-05-21 07:10 UTC
Labels: Bug report, Needs more info

**Comment by felixgoldstein** [comment] 2024-07-06 08:08
We have a similar problem. 
If I want to pay with TWINT and go to "Cancel payment" on the TWINT page.

<img width="1860" alt="Bildschirmfoto 2024-07-06 um 09 55 44" src="https://github.com/Adyen/adyen-shopware6/assets/1301766/98160920-989a-4038-a97d-e52a1e43d531">

The request to the Adyen endpoint `/checkoutshopper/checkoutPaymentReturn` is then repeated, but the second time the parameter `ady_status=cancelled` is missing

As a result, the FinishPage is displayed to the shopper and an order confirmation email is sent. However, the payment status of the order is correctly set to "canceled". 

The first request to the endpoint `/redirect-result` seems to be canceled by Adyen client wise. In my nginx access log I can see a `Status 499` log.  

Can you look at this again please?

Shopware: 6.4.0.9
Adyen: 3.11.0
