### ISSUE TITLE
[ECP-9424] There was an error with the payment method. Order number: [order-no] Missing data: non-nullable itemCategory cannot be null [] []

### ISSUE THREAD

**Issue by mcw-matthias** [Adyen/adyen-shopware6#524] opened 2024-07-25 07:51 UTC
**Describe the bug**
Customers who wish to pay via Adyen (e.g., via SOFORT) are unable to complete their payment. The following appears in the api.log: "There was an error with the payment method. Order number: [order-no] Missing data: non-nullable itemCategory cannot be null [] []". This error occurs with various products. The products have multiple categories assigned.

**Versions**
Shopware version: 6.5.8.12
Plugin version: 3.15.0

**To Reproduce**
1. Pay with Adyen
2. See api.log

**Expected behavior**
Payment should be possible.

**Screenshots**
![image](https://github.com/user-attachments/assets/d4cd7735-14c8-40c1-b81e-398261001e2c)

**Comment by candemiralp** [comment] 2024-08-22 13:13
Hello @mcw-matthias,

Thank you for raising this issue. This issue is related to Adyen PHP API Library and it has been fixed on [v18.2.1](https://github.com/Adyen/adyen-php-api-library/releases/tag/v18.2.1). We've already created a ticket to bump the version in [composer.json](https://github.com/Adyen/adyen-php-api-library/releases/tag/v18.2.1) file.

If the issue is urgent for you, please feel free to bump the library version to the [latest](https://github.com/Adyen/adyen-php-api-library/releases) on you composer file.

Best Regards,
Can

**Closed** 2024-09-09 13:37 UTC
