### ISSUE TITLE
Version bump of php-api-library in 3.16.X

### ISSUE THREAD

**Issue by phillensen** [Adyen/adyen-shopware6#573] opened 2024-11-21 14:30 UTC
**Describe the bug**
We are using Shopware 6.5 and thus version 3.16.x of the Shopware 6 Adyen plugin.
Currently this plugin is requiring package `adyen/php-api-library` with version `^17.5.0` 
```
"require": {
        "shopware/core": "~6.4.0 || ~6.5.0",
        "shopware/storefront": "~6.4.0 || ~6.5.0",
        "adyen/php-api-library": "^17.5.0",
        "adyen/php-webhook-module": "0.8.0",
        "ext-json": "*"
    },
```

We stumbled upon a bug that has already been fixed in adyen/php-api-library ([Link1](https://github.com/Adyen/adyen-php-api-library/pull/669), [Link2](https://github.com/Adyen/adyen-php-api-library/pull/669/files#diff-3e46c6beaa76494a8a54fe16089965cb01dfc60ea3cb89d1e615b2b4a0a47ff1L606)). 

Currently it is not possible to buy products that don't have an itemCategory. The result is that we have a lot of orders where the payment fails (i.e. with **Klarna Pay Now** and **Klarna Pay Later**, as they are using the _AbstractPaymentMethodHandler_.

I saw that the version of `adyen/php-api-library` was increased in the Shopware 6 Adyen plugin, but only for Version 4.1.X and above. And thus only for Shopware 6.6 shops and not for Shopare 6 shops running on SW 6.5. ([Link3](https://github.com/Adyen/adyen-shopware6/commit/e5ccf685d3e0ef3d0341b9ffbd4699fe1350daba#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L15)).

Is it possible to raise the the version of `adyen/php-api-library` to at least `18.2.1` in versions `3.16.X` so Shopware 6.5 shops can benefit from this bugfix too? ([Link4](https://github.com/Adyen/adyen-php-api-library/pull/670))

**Versions**
Shopware version: 6.5.8.13
Plugin version: 3.16.1

**To Reproduce**
1. Add a product to the cart that doesn't have an itemCategory
2. Go to checkout, select a payment method that is using AbstractPaymentMethodHandler (i.e. Klarna Pay Now or Klarna Pay Later) and finish checkout
3. The following error is thrown: `There was an error with the payment method. Order number: XXXXXXXXX Missing data: non-nullable itemCategory cannot be null [] []`
4. Customer gets redirected to page `/account/order/edit/0193448XXXXXXXXXXXXXe8b331e012?error-code=CHECKOUT__UNKNOWN_ERROR`, the order is placed, but the payment failed.

**Expected behavior**
Its possible to buy products without an itemCategory in a Shopware 6.5 shop.

**Comment by adyen-integrations-support** [comment] 2024-12-02 13:02
Hi @phillensen ,

We wanted to update you that we have successfully reproduced the issue locally and are currently investigating it further. We will keep you informed as soon as we have more details or a resolution.

Thank you for your patience.

Best regards

**Comment by Gugiman** [comment] 2024-12-05 07:49
I think it's the same issue like here.
But it was only fixed for the plugin compatible with Shopware 6.6

https://github.com/Adyen/adyen-shopware6/issues/524

**Comment by adyen-integrations-support** [comment] 2024-12-09 13:18
Hi @phillensen ,

We want to let you know that we are actively working on this ticket and are in the process of identifying the root cause of the problem.

As soon as we have more information or a resolution, we will update you. We appreciate your patience and understanding in the meantime.

Best regards

**Comment by adyen-integrations-support** [comment] 2024-12-12 09:31
Hi @phillensen ,

We want to inform you that the fix for this issue will be included in the next plugin release.

Thank you for your patience, and please let us know if you have any further questions.

Best regards

**Comment by BuW-Team-IT** [comment] 2024-12-19 13:19
@adyen-integrations-support Is this the open merge request for this fix?

https://github.com/Adyen/adyen-shopware6/pull/542

When can i expect the next release?

Thank you!

**Comment by phillensen** [comment] 2024-12-19 13:21
@adyen-integrations-support Is this the open merge request for this fix? https://github.com/Adyen/adyen-shopware6/pull/542

When can i expect the next release?

Thank you!

**Comment by phillensen** [comment] 2024-12-19 13:21
@adyen-integrations-support Is this the open merge request for this fix? https://github.com/Adyen/adyen-shopware6/pull/542

When can i expect the next release?

Thank you!

**Closed** 2024-12-19 15:17 UTC
