### ISSUE TITLE
[ECP-9199] Order edit flow breaks when using Adyen plugin

### ISSUE THREAD

**Issue by wannevancamp** [Adyen/adyen-shopware6#485] opened 2024-04-25 09:17 UTC
**Describe the bug**
When editing an order in the Shopware admin a 500 is thrown. 

```
Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (db24301.adyen_payment, CONSTRAINT fk.adyen_payment.order_transaction_id FOREIGN KEY (order_transaction_id) REFERENCES order_transaction (id))" at /.../vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 56 {"exception":"[object] (Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException(code: 1451): An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (db24301.adyen_payment, CONSTRAINT fk.adyen_payment.order_transaction_id FOREIGN KEY (order_transaction_id) REFERENCES order_transaction (id)) at /.../vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:56)\n[previous exception] [object] (Doctrine\DBAL\Driver\PDO\Exception(code: 1451): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (db24301.adyen_payment, CONSTRAINT fk.adyen_payment.order_transaction_id FOREIGN KEY (order_transaction_id) REFERENCES order_transaction (id)) at /.../vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (db24301.adyen_payment, CONSTRAINT fk.adyen_payment.order_transaction_id FOREIGN KEY (order_transaction_id) REFERENCES order_transaction (id)) at /v.../vendor/doctrine/dbal/src/Driver/PDO/Statement.php:121)"} []
```

**Solution**
The adyen_payment table needs to be versioned because there is a reference tot the order_tranaction table.

**Versions**
Shopware version: all
Plugin version: all

**To Reproduce**
1. Go to the order detail page in the Shopware admin
2. Click on edit order
3. Edit order ex. add a tag.
4. Order can't be safed
5. See error

**Expected behavior**
Order can be saved

**Comment by RokPopov** [comment] 2024-05-16 07:55
Hi @wannevancamp,

Thank you for reporting this issue. I create an internal ticket to investigate and come up with a solution. Once the solution is implemented and merged with the `develop` branch, this ticket will automatically be closed.

Kind regards,
Rok

**Comment by romaneckert** [comment] 2024-08-09 11:26
Hello @RokPopov, Hello @wannevancamp 

I have noticed a similar error in this context. If you open the order in the Shopware backend and close and reopen it, Shopware tries to delete the previous version. The same error is generated. As a result, every time you open the order in the Shopware backend, a new version of the order is created in the database, even though nothing has changed.

Tested Versions
Shopware version: 6.5.8.11
Plugin version: 3.15.0

API Call: 
/api/_action/version/{{versionId}}/order/{{orderId}}

```
{
    "errors": [
        {
            "code": "1451",
            "status": "500",
            "title": "Internal Server Error",
            "detail": "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`shop`.`adyen_payment`, CONSTRAINT `fk.adyen_payment.order_transaction_id` FOREIGN KEY (`order_transaction_id`) REFERENCES `order_transaction` (`id`))"
        }
    ]
}
```

This is a very critical bug and should be fixed as soon as possible.

Kind regards

**Comment by alessandroaussems** [comment] 2024-08-20 06:11
@RokPopov  Almost 3 months later... Any update on this?

**Comment by adyen-integrations-support** [comment] 2024-10-02 13:29
Hey @wannevancamp,

Please note that our team tried to reproduce the issue and we were not able to get the same issue as you described.
Can you please give us more information so our team can investigate further?

Do you still experience the same issue at the moment? What is the plugin and system version you are using? It would be helpful if you can share screenshots and screencasts with us. 

Thank you!

**Comment by cwittstock** [comment] 2024-10-14 19:08
We have the same issue, when we change the state of an order:

```
[2024-10-14T07:54:07.933219+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`shopware_safety_live`.`adyen_payment`, CONSTRAINT `fk.adyen_payment.order_transaction_id` FOREIGN KEY (`order_transaction_id`) REFERENCES `order_transaction` (`id`))" at ExceptionConverter.php line 56 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 1451): An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`shopware_safety_live`.`adyen_payment`, CONSTRAINT `fk.adyen_payment.order_transaction_id` FOREIGN KEY (`order_transaction_id`) REFERENCES `order_transaction` (`id`)) at /.../vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:56)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1451): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`shopware_safety_live`.`adyen_payment`, CONSTRAINT `fk.adyen_payment.order_transaction_id` FOREIGN KEY (`order_transaction_id`) REFERENCES `order_transaction` (`id`)) at /.../vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`shopware_safety_live`.`adyen_payment`, CONSTRAINT `fk.adyen_payment.order_transaction_id` FOREIGN KEY (`order_transaction_id`) REFERENCES `order_transaction` (`id`)) at /.../vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} []
```

Shopware Version:  6.5.8.14 
Adyen Plugin: 3.16.1

What else do you need to identify the problem?

**Comment by Gugiman** [comment] 2024-10-15 12:52
We also get this error.
I can't determine on which processes exactly but it appears on several occasions while running.
But all in relation to the order being processed.

**Comment by adyen-integrations-support** [comment] 2024-11-25 15:22
Hey,

In order to further investigate this issue, our team would need to log into your shop and examine the reported problem since it can not be reproduced in our environment.

Please do not share the credentials of your store directly on GitHub or through email.
Please, submit your query through our regular support channels by going to https://www.adyen.help/hc/en-us/requests/new  or by sending an e-mail to [[support@adyen.com](mailto:support@adyen.com)] (mailto:[support@adyen.com](mailto:support@adyen.com)).

Alternatively, you can also submit your request through the Support section of your Adyen Customer Area.

Please note that you will first communicate with the first level of support, after which the second level of support will be involved. Make sure to provide a detailed explanation of the issue you are having. Please add the screenshots, plugin version, Prestashop version, steps to reproduce, Adyen and shop logs, or anything else that can help us in our investigation.

We will close this ticket here. If you have any questions or concerns, please let us know.

Kind regards

**Closed** 2024-11-25 15:22 UTC
