### ISSUE TITLE
JavaScript Error: Component could not mount. Root node was not found.

### ISSUE THREAD

**Issue by andydandy80** [Adyen/adyen-shopware6#574] opened 2024-11-26 16:01 UTC
**Describe the bug**
I got a error on checkout page after selecting the payment method and clicking on "complete order" button. Nothing happens, in console we say an Javascript error.

**Versions**
Shopware version: 6.6.8.2
Plugin version: 4.1.3

**Error Message**
Error: Component could not mount. Root node was not found.
    at r.value (BaseElement.ts:110:19)
    at o.handlePaymentAction (adyen-payment-shopware6.js?1732635545:1:28988)
    at XMLHttpRequest.<anonymous> (adyen-payment-shopware6.js?1732635545:1:8554)

**Screenshots**
![checkout](https://github.com/user-attachments/assets/8606b5a5-7a88-4e2f-9f1e-3bb4fc47f49a)
![console](https://github.com/user-attachments/assets/36e62fdf-86ae-4c50-bec2-a65c91e30c66)

**Additional**
The Bug was described here in a previous version: https://github.com/Adyen/adyen-shopware6/issues/251
Closed without any comment.

**Comment by adyen-integrations-support** [comment] 2024-11-27 12:45
Hi @andydandy80 ,

While we couldn't reproduce this problem in our local environment, we were able to do it in your shop using the link provided in your screenshots.

https://tagesgaestekarte.foehr.de/stage6/public/

To investigate further and identify the root cause, we request your permission to make test orders in your shop.

Please let us know if this is acceptable or if you need any additional information from us.

Best regards

**Comment by andydandy80** [comment] 2024-11-27 13:02
Sure, no problem. It is configured as a test environment.

**Comment by andydandy80** [comment] 2024-11-28 15:37
Any new insights?

**Comment by adyen-integrations-support** [comment] 2024-12-02 11:36
Hi @andydandy80 ,

We are actively investigating the issue you reported. As soon as we have more information, we will reach out to you.

Thank you for your patience and understanding.

Best regards

**Comment by adyen-integrations-support** [comment] 2024-12-04 08:42
Hi,

Our team has reviewed your shop and identified that the Adyen plugin’s extension for the checkout/confirm page is not being loaded. This extension is responsible for adding the modal required for various Adyen payment methods, such as 3D Secure cards.

Due to the absence of this modal on the checkout page, the Adyen JavaScript cannot mount the necessary web components to complete the payment process.

Since your store uses a custom theme and potentially other plugins that modify this page, we cannot determine the exact reason why the Adyen extension is not rendering.

To investigate further, we would need backoffice and FTP access to your staging store. This will allow us to analyze the issue in more detail and identify the root cause.

Please, do not share your store's credentials directly on GitHub or through email.
Please, submit your query through our regular support channels by going to https://www.adyen.help/hc/en-us/requests/new  or by sending an e-mail to [[support@adyen.com](mailto:support@adyen.com)](mailto:[support@adyen.com](mailto:support@adyen.com)).
Alternatively, you can also submit your request through the Support section of your Adyen Customer Area.

Note that you will first communicate with the first level of support, after which the second level of support will be involved. Make sure to provide a detailed explanation of the issue you are having. Please add the screenshots, plugin version, Prestashop version, steps to reproduce, Adyen and shop logs, or anything else that can help us in our investigation.

If you have any questions or concerns, please let us know.

Best regards

**Closed** 2024-12-04 11:09 UTC
