### ISSUE TITLE
Date format on potential NULL values in the admincontroller can result in critical error

### ISSUE THREAD

**Issue by timkoopmans50** [Adyen/adyen-shopware6#377] opened 2023-04-26 09:51 UTC
**Describe the bug**
Sometimes the createdAt and updatedAt colums are NULL. No type test is done in the adminController resulting in a critical error. 

**Versions**
Shopware version: -
Plugin version: 3.10.1 / 3.11

**Expected behavior**
tested values before formatting them here : https://github.com/Adyen/adyen-shopware6/blob/develop/src/Controller/AdminController.php#L421 and here https://github.com/Adyen/adyen-shopware6/blob/develop/src/Controller/AdminController.php#L422

**Comment by candemiralp** [comment] 2023-05-01 06:01
Hello @timkoopmans50,

Closing this ticket since it is a duplicate of #270. You can check the updates on the first Github issue.

Best Regards,
Can

**Closed by candemiralp** 2023-05-01 06:01 UTC
