### ISSUE TITLE
[PW-8467] Payment methods in cart not shown or marked as not available

### ISSUE THREAD

**Issue by andydandy80** [Adyen/adyen-shopware6#388] opened 2023-06-05 08:26 UTC
In shopping cart is under the order items a section for calculating the shipping costs depending on payment method and shipping method. The payment methods there are not complete or marked as "not available". On final checkout page all payment methods are correct shown.

I have investigated it and found following critical code parts:
src/Subscriber/PaymentSubscriber.php, Function onShoppingCartLoaded and there "$this->paymentMethodsFilterService->getAvailableGiftcards"

src/Service/PaymentMethodsFilterService.php, Function "getAvailableGiftcards". Here in the foreach loop all payments are removed.

Shopware version: 6.4.20.2
Plugin version: 3.11.0

Cart (../checkout/cart):
![grafik](https://github.com/Adyen/adyen-shopware6/assets/45691258/a1357e61-804b-4371-b429-acc9abb6f967)

Checkout (../checkout/confirm):
![grafik](https://github.com/Adyen/adyen-shopware6/assets/45691258/d8dca750-4c48-4375-98ef-1ccec27d7d83)

**Comment by candemiralp** [comment] 2023-06-09 08:24
Hello @andydandy80,

Thanks for raising this issue. We successfully reproduced the issue and created an investigation ticket to solve it. You will be informed when it is done.

Best Regards,
Can

**Comment by adyen-integrations-support** [comment] 2024-11-13 14:28
Hello @candemiralp,

Please note that we were unable to reproduce this issue in the latest plugin version (3.16.3), therefore it will be closed as resolved.

Payment methods that are labeled as not available on the /checkout/cart page are not displayed on the /checkout/confirm page.

If you can reproduce the issue again, feel free to re-open this ticket.

Thank you,

Kind regards.

**Closed** 2024-11-13 14:31 UTC
Labels: Bug report
