### ISSUE TITLE
[PW-7212] Uncaught PHP Exception Shopware\Core\Checkout\Payment\Exception\UnknownPaymentMethodException

### ISSUE THREAD

**Issue by MelvinAchterhuis** [Adyen/adyen-shopware6#276] opened 2022-07-27 07:40 UTC
**Describe the bug**
When we have the Adyen plugin installed we can't use manual created payment methods anymore (Invoice, Pay at delivery, Pay at pickup etc.). The user gets redirect to /checkout/order with a 404 message.

The following error is visible in the logs:

`request.ERROR: Uncaught PHP Exception Shopware\Core\Checkout\Payment\Exception\UnknownPaymentMethodException: "The payment method 1a116955b1294a45a64aa6e1507e9028 could not be found." at /var/domains/domain.com/application/vendor/shopware/core/Checkout/Payment/PreparedPaymentService.php line 56 {"exception":"[object] (Shopware\\Core\\Checkout\\Payment\\Exception\\UnknownPaymentMethodException(code: 0): The payment method 1a116955b1294a45a64aa6e1507e9028 could not be found. at /var/domainsdomain.com/application/vendor/shopware/core/Checkout/Payment/PreparedPaymentService.php:56)"} []`

**Versions**
Shopware version: 6.4.11.1
Plugin version: 3.4.2

**To Reproduce**
1. Pay with manually created payment method
2. Error above is thrown

**Expected behavior**
Payment is handled by merchant, customer sees the confirm/finish page instead of a 404 error

**Comment by peterojo** [comment] 2022-08-05 14:40
Hi @MelvinAchterhuis we reverted all references to `Checkout/Payment/PreparedPaymentService.php` for the 3.4.2 release, could you check to see if removing the plugin and reinstalling it from scratch in version 3.4.2 fixes this issue?

**Comment by jakub-groncki** [comment] 2022-09-09 11:23
This still does not work in the latest release (3.6.0) with the same scenario.

**Comment by peterojo** [comment] 2022-09-09 12:02
Hi @MelvinAchterhuis can you share the logs from the Adyen plugin? You would find them in `var/logs/adyen`. So we can see where the plugin interacts with your custom payment method.

**Comment by jakub-groncki** [comment] 2022-09-12 10:33
@peterojo if I may too:

```
api.log

[2022-09-12T08:15:06.747084+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:15:06.747297+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"Foodspring_DE","countryCode":"GB","amount":{"currency":"GBP","value":2519},"shopperReference":"738bf2056ecf41eb9e0c555be058a586","shopperLocale":"en-GB"} [] []
[2022-09-12T08:15:07.160035+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000203966","merchantName":"foodspring GmbH"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"Foodspring_DE"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
[2022-09-12T08:15:22.234679+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:15:22.234828+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"Foodspring_DE","countryCode":"GB","amount":{"currency":"GBP","value":2519},"shopperReference":"738bf2056ecf41eb9e0c555be058a586","shopperLocale":"en-GB"} [] []
[2022-09-12T08:15:22.681165+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000203966","merchantName":"foodspring GmbH"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"Foodspring_DE"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
[2022-09-12T08:28:10.629200+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:28:10.629377+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"Foodspring_DE","countryCode":"GB","amount":{"currency":"GBP","value":2389},"shopperReference":"c80d933c356240fea3156627f2a8110f","shopperLocale":"en-GB"} [] []
[2022-09-12T08:28:11.200893+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000203966","merchantName":"foodspring GmbH"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"Foodspring_DE"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
[2022-09-12T08:28:21.081703+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:28:21.081868+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"Foodspring_DE","countryCode":"GB","amount":{"currency":"GBP","value":2389},"shopperReference":"c80d933c356240fea3156627f2a8110f","shopperLocale":"en-GB"} [] []
[2022-09-12T08:28:21.400122+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000203966","merchantName":"foodspring GmbH"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"Foodspring_DE"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
[2022-09-12T08:44:52.572725+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:44:52.573149+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"Foodspring_DE","countryCode":"GB","amount":{"currency":"GBP","value":2389},"shopperReference":"c80d933c356240fea3156627f2a8110f","shopperLocale":"en-GB"} [] []
[2022-09-12T08:44:52.824206+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000203966","merchantName":"foodspring GmbH"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"Foodspring_DE"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
```

```
adyen.log

[2022-09-05T14:41:39.484738+00:00] adyen_generic.ERROR: Invalid Merchant Account [] []
[2022-09-05T14:41:39.680105+00:00] adyen_generic.ERROR: Invalid Merchant Account [] []
```

There is nothing specific in the logs. I've traced it down to `PaymentHandlerRegistry::handlers` not containing the manual payment method's `handler_identifier` or not being equal to `$expectedHandlerType`. In both cases, it stems from `PreparedPaymentService`. In and of itself it's not bad that `PreparedPaymentService` is called but somewhere along the call stack something's being deleting data from `handlers`.

**Comment by jakub-groncki** [comment] 2022-09-12 10:36
@peterojo if I may too:

```
api.log

[2022-09-12T08:15:06.747084+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:15:06.747297+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"XXX","countryCode":"GB","amount":{"currency":"GBP","value":2519},"shopperReference":"738bf2056ecf41eb9e0c555be058a586","shopperLocale":"en-GB"} [] []
[2022-09-12T08:15:07.160035+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000000000","merchantName":"XXX"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"XXX"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
[2022-09-12T08:15:22.234679+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:15:22.234828+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"XXX","countryCode":"GB","amount":{"currency":"GBP","value":2519},"shopperReference":"738bf2056ecf41eb9e0c555be058a586","shopperLocale":"en-GB"} [] []
[2022-09-12T08:15:22.681165+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000000000","merchantName":"XXX"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"XXX"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
[2022-09-12T08:28:10.629200+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:28:10.629377+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"XXX","countryCode":"GB","amount":{"currency":"GBP","value":2389},"shopperReference":"c80d933c356240fea3156627f2a8110f","shopperLocale":"en-GB"} [] []
[2022-09-12T08:28:11.200893+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000000000","merchantName":"XXX"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"XXX"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
[2022-09-12T08:28:21.081703+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:28:21.081868+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"XXX","countryCode":"GB","amount":{"currency":"GBP","value":2389},"shopperReference":"c80d933c356240fea3156627f2a8110f","shopperLocale":"en-GB"} [] []
[2022-09-12T08:28:21.400122+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000000000","merchantName":"XXX"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"XXX"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
[2022-09-12T08:44:52.572725+00:00] adyen_api.INFO: Request url to Adyen: https://checkout-test.adyen.com/checkout/v68/paymentMethods [] []
[2022-09-12T08:44:52.573149+00:00] adyen_api.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"XXX","countryCode":"GB","amount":{"currency":"GBP","value":2389},"shopperReference":"c80d933c356240fea3156627f2a8110f","shopperLocale":"en-GB"} [] []
[2022-09-12T08:44:52.824206+00:00] adyen_api.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["visa","mc"],"name":"Credit Card","type":"scheme"},{"brands":["visa","mc"],"configuration":{"merchantId":"000000000000000","merchantName":"XXX"},"name":"Apple Pay","type":"applepay"},{"configuration":{"merchantId":"50","gatewayMerchantId":"XXX"},"name":"Google Pay","type":"paywithgoogle"}]} [] []
```

```
adyen.log

[2022-09-05T14:41:39.484738+00:00] adyen_generic.ERROR: Invalid Merchant Account [] []
[2022-09-05T14:41:39.680105+00:00] adyen_generic.ERROR: Invalid Merchant Account [] []
```

There is nothing specific in the logs. I've traced it down to `PaymentHandlerRegistry::handlers` not containing the manual payment method's `handler_identifier` or not being equal to `$expectedHandlerType`. In both cases, it stems from `PreparedPaymentService`. In and of itself it's not bad that `PreparedPaymentService` is called but somewhere along the call stack something's being deleting data from `handlers`.

**Comment by jakub-groncki** [comment] 2022-09-16 10:27
@peterojo Could you check out my comment? Thanks a lot in advance!

**Comment by peterojo** [comment] 2022-09-16 13:28
Hi @jakub-groncki, my apologies for the delay,
I see no issues from the `api.log` logs you sent, and the `adyen.log` you sent has a 7 days earlier timestamp (as you mentioned, this was before configuring the merchant account) so no issues there either that would cause any payment methods to fail.
Maybe I'm missing something, but could you please explain the steps to "manually" create a payment method? Could it be that your custom payment method is missing a `handler_identifier`?

**Comment by jakub-groncki** [comment] 2022-09-16 14:24
I'm doing a very simple thing:

Settings -> Payment -> Add payment method

I fill in the name and save it. Then I assign it to the sales channel. After that, when selecting it at checkout (it's visible there) I'm getting the error mentioned by @MelvinAchterhuis. So there's not much to it besides that. It does have the handle identifier in the db.

**Comment by peterojo** [comment] 2022-09-20 08:39
Hi @jakub-groncki thanks for the update, I have been able to reproduce the issue with the plugin installed, I'll troubleshoot a bit and get back to you when I have found the cause and fixed it

**Comment by peterojo** [comment] 2022-09-22 04:24
@MelvinAchterhuis @jakub-groncki FYI, I found the issue and fixed it in the mentioned PR, we will release soon. You can also apply this fix anytime on your installation to get it working.

**Closed** 2022-09-22 14:50 UTC
