### ISSUE TITLE
Payment status not changed to Paid after receiving Authorisation notification

### ISSUE THREAD

**Issue by erwinn** [Adyen/adyen-shopware6#364] opened 2023-03-23 14:48 UTC
**Describe the bug**
Customer is paying the order with Credit card, payment status changed to Authorized. A minute later, webshop receives the AUTHORISATION notification successfully. In webshop logs it is visible the webhook is handled successfully and payment status should have been changed from Authorized to Paid. Unfortunately that transition is not visible, order remains in 'Authorized' state.

![image](https://user-images.githubusercontent.com/10939597/227239750-baed315d-a247-4338-b2f8-100b17c4322b.png)

Logs show the webhook has been handled successfully

![image](https://user-images.githubusercontent.com/10939597/227240809-9e17985b-45d5-4b83-9610-23372d642980.png)

**Versions**
Shopware version: 6.4.20.0
Plugin version: 3.10.1

**To Reproduce**
1. Place order
2. Check payment status
3. Process incoming webhooks
4. Payment status should have been updated, but it's not

**Expected behavior**
Expect payment status transition from 'Authorized' to 'Paid' to happen automatically. It is currently not the case.

![image](https://user-images.githubusercontent.com/10939597/227240444-2ca44ff8-d847-4811-8ff6-ca0fee4e1d8d.png)

**Desktop (please complete the following information):**
 - OS: Windows/Ubuntu
 - Browser Chrome
 - Version: newest

**Comment by candemiralp** [comment] 2023-04-24 12:07
Hello @erwinn,

Thank you for opening this issue and apologies for the late reply. Unfortunately, we were not able to reproduce the issue that you described. On the test cases, payment status went to `Paid` successfully on our instances.

I would recommend checking [this](https://github.com/Adyen/adyen-shopware6/blob/2e696092a5e1ea6933d2da5df0e642f9ddb945da/src/ScheduledTask/Webhook/AuthorisationWebhookHandler.php#L139) condition block and values `transactionAmount` & `intval($notification->getAmountValue())`. If those are not match, `TransactionStateHandler` on [this](https://github.com/Adyen/adyen-shopware6/blob/2e696092a5e1ea6933d2da5df0e642f9ddb945da/src/ScheduledTask/Webhook/AuthorisationWebhookHandler.php#L157) line is unreachable.

I am closing this issue since the issue is not reproducible on our instances and not referring to a code block. If the issue is persistent after the above suggestion, I would recommend sending an email to our support team via support@adyen.com with the logs containing the issue. We don't want you to share the logs on Github since they may carry sensitive information.

Best Regards,
Can

**Closed by candemiralp** 2023-04-24 12:07 UTC
