### ISSUE TITLE
[ECP-8841] AbstractPaymentMethodHandler breaks the payment flow in Shopware checkout

### ISSUE THREAD

**Issue by bitfactory-michel-lubbers** [Adyen/adyen-shopware6#402] opened 2023-07-21 09:24 UTC
**Describe the bug**

**Versions**
Shopware version: 6.4.20
Plugin version: [3.8.1, ...]

**To Reproduce**
Because our env is behind a restricted environment i will explain in details what to do
1. In shopware admin create a product without a category assigned
2. In the front-end of shopware place that product in cart.
3. Go to checkout
4. Choose delivery time
5. Choose Klarna Pay Later as payment method
6. Place the order
7. It will return with error 'Call to a member function getName() on null'

**Expected behavior**
That order is placed and that you are directed to the Klarna payment platform.

**Screenshots**
![image](https://github.com/Adyen/adyen-shopware6/assets/100353261/8c342d1b-6aef-4e37-9a67-63a108840362)
![image](https://github.com/Adyen/adyen-shopware6/assets/100353261/d23345da-a269-4729-a3d0-d6d88a2693b4)

**Additional context**
I found out that it happens in the AbstractPaymentMethodHandler.php file.
In version 3.8.1 and 3.9.0 you have the following code:
```$product->getCategories() ? $product->getCategories()->first()->getName() : null```
$product->getCategories() is always true because it returns a `CategoryCollection`

In the later versions you are doing ```if (!is_null($product->getCategories())) { ```
Which is also true because of the `CategoryCollection` response.

Instead it should be this ```$product->getCategories()->count() > 0```

**Comment by phillensen** [comment] 2023-11-24 12:00
I can confirm this bug. Can you please provide a fix for this? Otherwise we can't offer they payment method **Klarna - Pay Later** to our customers.

Attached you have a screencast which explains this bug in 3 minutes:
https://www.loom.com/share/d731808370c8432387e4cbf73989bcbe

We are using:
Shopware version: 6.4.17.1
Plugin version: 3.10.0

**Comment by candemiralp** [comment] 2023-12-22 10:13
Hello @bitfactory-michel-lubbers,

Thank you for raising this issue. We've created an internal ticket to solve this issue. You will be informed when the implementation is done.

Thank you @phillensen for providing the screen recording of the issue.

Best Regards,
Can

**Comment by phillensen** [comment] 2024-01-24 15:32
@candemiralp @hossam-adyen I think this issue might be a duplicate of #450.

**Comment by candemiralp** [comment] 2024-01-25 10:13
Hello @phillensen @bitfactory-michel-lubbers,

This issue has been resolved in #452. After merging that PR, this issue will be closed. Thank you for your contribution.

Best Regards,
Can

**Closed** 2024-02-07 09:26 UTC
Labels: Bug report
